import { TimelineData } from './Timeline.types';

export const TIMELINE_DATA: TimelineData = {
  edu: [
    {
      id:          'edu-1',
      title:       'Ciência da Computação',
      institution: 'Universidade Cruzeiro do Sul',
      period:      '2023 — 2026',
      status:      'Cursando',
      statusType:  'active',
      description: 'Graduação com foco em algoritmos, banco de dados, sistemas operacionais e segurança da informação. Desenvolvimento de habilidades técnicas e trabalho em equipe para desafios reais da indústria.',
      tags:        ['Back-end', 'Front-end', 'Algoritmos', 'Banco de Dados'],
      certUrl:     null,
    },
    {
      id:          'edu-2',
      title:       'Desenvolvimento de Sistemas',
      institution: 'ETEC — Escola Técnica Estadual',
      period:      '2020 — 2022',
      status:      'Concluído',
      statusType:  'done',
      description: 'Curso técnico integrado ao médio com base sólida em programação, desenvolvimento de aplicações e banco de dados. TCC HomeMade Gourmet aprovado com louvor.',
      tags:        ['Programação', 'Web', 'Banco de Dados'],
      certUrl:     '/docs/etec.pdf',
    },
  ],
  cert: [
    {
      id:          'cert-1',
      title:       'CC50 — Ciência da Computação',
      institution: 'Harvard University · Fundação Estudar',
      period:      '2025',
      status:      'Concluído',
      statusType:  'done',
      description: 'Versão em português do CS50 de Harvard. Lógica de programação com C e Python, estruturas de dados, SQL, desenvolvimento web com Flask e introdução à IA.',
      tags:        ['C', 'Python', 'Algoritmos', 'SQL', 'Flask'],
      certUrl:     'https://www.linkedin.com/in/oguilherme-cruz/details/certifications/',
    },
    {
      id:          'cert-2',
      title:       'Discover — Trilha Fundamentar',
      institution: 'Rocketseat',
      period:      '2024',
      status:      'Concluído',
      statusType:  'done',
      description: 'Formação completa em desenvolvimento web e mobile com HTML, CSS, JavaScript, React e Node.js — foco em resolução de problemas e código escalável.',
      tags:        ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
      certUrl:     'https://app.rocketseat.com.br/certificates/5e1a87e2-9e71-4dbd-82a1-52f98b99c984',
    },
    {
      id:          'cert-3',
      title:       'Modelagem de Dados',
      institution: 'SENAI',
      period:      '2021',
      status:      'Concluído',
      statusType:  'done',
      description: 'Estruturação de informações com diagramas e técnicas para criação de bancos de dados funcionais. Análise de dados e modelagem de sistemas tecnológicos.',
      tags:        ['SQL', 'Modelagem', 'Banco de Dados'],
      certUrl:     '/docs/modelagem-de-dados.pdf',
    },
  ],
  exp: [
    {
      id:          'exp-1',
      title:       'Atendente de Suporte Técnico',
      institution: 'Wise System · CLT',
      period:      'Jan 2026 — Presente',
      status:      'Atual',
      statusType:  'active',
      description: 'Suporte técnico via telefone, chat, e-mail e acesso remoto. Homologação de integrações NFS-e e CNAB. Gerenciamento de chamados no ServiceDesk interno (SIGO).',
      tags:        ['Suporte', 'NFS-e', 'CNAB', 'Service Desk', 'SIGO'],
      certUrl:     null,
    },
    {
      id:          'exp-2',
      title:       'Estagiário de Suporte Técnico',
      institution: 'Wise System · Estágio',
      period:      'Abr 2025 — Dez 2025',
      status:      'Concluído',
      statusType:  'done',
      description: 'Atendimento presencial em São Paulo. Suporte técnico ao cliente, documentação de chamados e apoio ao time de implantação do software SIGO.',
      tags:        ['Suporte', 'Atendimento', 'SIGO'],
      certUrl:     null,
    },
  ],
};
